import type { SubtitleStyle } from "./style-types";
import { DEFAULT_SUBTITLE_STYLE } from "./style-types";

export interface SubtitlePreset {
	id: string;
	name: string;
	description: string;
	style: SubtitleStyle;
}

export const SUBTITLE_PRESETS: SubtitlePreset[] = [
	{
		id: "capcut",
		name: "CapCut",
		description: "Bold yellow with black outline — TikTok/Reels style",
		style: {
			...DEFAULT_SUBTITLE_STYLE,
			fontFamily: "Inter",
			fontSize: 36,
			fontWeight: 800,
			color: "#ffeb3b",
			backgroundColor: "#000000",
			backgroundOpacity: 0.7,
			outlineColor: "#000000",
			outlineWidth: 3,
			shadowColor: "#000000",
			shadowBlur: 6,
			shadowOffsetX: 0,
			shadowOffsetY: 3,
			position: "bottom",
			verticalOffset: -20,
			horizontalOffset: 0,
			animation: "none",
			animationDuration: 0.2,
			lineHeight: 1.3,
			letterSpacing: 1,
			textAlign: "center",
			presetId: "capcut",
		},
	},
	{
		id: "classic",
		name: "Classic",
		description: "White text with subtle shadow — traditional subtitle style",
		style: {
			...DEFAULT_SUBTITLE_STYLE,
			fontFamily: "Arial",
			fontSize: 28,
			fontWeight: 400,
			color: "#ffffff",
			backgroundColor: "#000000",
			backgroundOpacity: 0.5,
			outlineColor: "#000000",
			outlineWidth: 1,
			shadowColor: "#000000",
			shadowBlur: 3,
			shadowOffsetX: 0,
			shadowOffsetY: 1,
			position: "bottom",
			verticalOffset: 0,
			horizontalOffset: 0,
			animation: "fade",
			animationDuration: 0.3,
			lineHeight: 1.5,
			letterSpacing: 0,
			textAlign: "center",
			presetId: "classic",
		},
	},
	{
		id: "modern",
		name: "Modern",
		description: "Clean sans-serif with rounded background pill",
		style: {
			...DEFAULT_SUBTITLE_STYLE,
			fontFamily: "Inter",
			fontSize: 30,
			fontWeight: 600,
			color: "#ffffff",
			backgroundColor: "#1a1a2e",
			backgroundOpacity: 0.8,
			outlineColor: "transparent",
			outlineWidth: 0,
			shadowColor: "#000000",
			shadowBlur: 8,
			shadowOffsetX: 0,
			shadowOffsetY: 4,
			position: "bottom",
			verticalOffset: -40,
			horizontalOffset: 0,
			animation: "slide",
			animationDuration: 0.4,
			lineHeight: 1.4,
			letterSpacing: 0.5,
			textAlign: "center",
			presetId: "modern",
		},
	},
	{
		id: "karaoke",
		name: "Karaoke",
		description: "Word-by-word highlight animation — sing-along style",
		style: {
			...DEFAULT_SUBTITLE_STYLE,
			fontFamily: "Inter",
			fontSize: 34,
			fontWeight: 700,
			color: "#e0e0e0",
			backgroundColor: "#000000",
			backgroundOpacity: 0.6,
			outlineColor: "#000000",
			outlineWidth: 2,
			shadowColor: "#000000",
			shadowBlur: 4,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			position: "bottom",
			verticalOffset: -10,
			horizontalOffset: 0,
			animation: "karaoke",
			animationDuration: 0.5,
			lineHeight: 1.4,
			letterSpacing: 0,
			textAlign: "center",
			presetId: "karaoke",
		},
	},
];

export function getSubtitlePreset(id: string): SubtitleStyle | undefined {
	return SUBTITLE_PRESETS.find((p) => p.id === id)?.style;
}
